import React, { createContext, useContext, useState, useEffect } from 'react';

const STORAGE_KEY = 'lw_settings';

const DEFAULTS = {
  profile: {
    firstName: 'Global',
    lastName:  'Partnership Manager',
    email:     'global@loveworld.com',
    phone:     '+1 (555) 000-0000',
    role:      'Global Partnership Manager',
    region:    'Global',
    timezone:  'UTC+0',
  },
  security:      { twoFactor: false },
  notifications: {
    reportDue: true, reportSubmitted: true,
    missingSubmit: true, newTemplate: false,
    financeUpdates: true, systemAlerts: true,
  },
  preferences: {
    language:   'English',
    dateFormat: 'MM/DD/YYYY',
    currency:   'USD ($)',
    theme:      'light',
  },
  privacy: {
    activityLogging: true, analyticsTracking: false, profileVisibility: true,
  },
};

function loadSettings() {
  try {
    const raw = sessionStorage.getItem(STORAGE_KEY);
    if (!raw) return DEFAULTS;
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object') return DEFAULTS;
    return {
      profile:       { ...DEFAULTS.profile,       ...(parsed.profile       || {}) },
      security:      { ...DEFAULTS.security,       ...(parsed.security      || {}) },
      notifications: { ...DEFAULTS.notifications,  ...(parsed.notifications || {}) },
      preferences:   { ...DEFAULTS.preferences,    ...(parsed.preferences   || {}) },
      privacy:       { ...DEFAULTS.privacy,        ...(parsed.privacy       || {}) },
    };
  } catch {
    sessionStorage.removeItem(STORAGE_KEY);
    return DEFAULTS;
  }
}

export function applyTheme(theme) {
  const root = document.documentElement;
  if (theme === 'system') {
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    root.setAttribute('data-theme', prefersDark ? 'dark' : 'light');
  } else {
    root.setAttribute('data-theme', theme);
  }
}

// Maps our language names to BCP-47 locale codes
export const LANGUAGE_LOCALE_MAP = {
  'English':    'en-US',
  'French':     'fr-FR',
  'Portuguese': 'pt-BR',
  'Spanish':    'es-ES',
  'Yoruba':     'yo-NG',
  'Hindi':      'hi-IN',
  'Russian':    'ru-RU',
  'Chinese':    'zh-CN',   // Mandarin Simplified
  'Bengali':    'bn-BD',
  'Arabic':     'ar-SA',   // Modern Standard Arabic (RTL)
  'Indonesian': 'id-ID',
};

// Languages that use right-to-left (RTL) text direction
export const RTL_LANGUAGES = new Set(['Arabic']);

// Maps our date format labels to format functions
export const DATE_FORMAT_FN = {
  'MM/DD/YYYY': (d) => {
    const dt = d instanceof Date ? d : new Date(d);
    return `${String(dt.getMonth()+1).padStart(2,'0')}/${String(dt.getDate()).padStart(2,'0')}/${dt.getFullYear()}`;
  },
  'DD/MM/YYYY': (d) => {
    const dt = d instanceof Date ? d : new Date(d);
    return `${String(dt.getDate()).padStart(2,'0')}/${String(dt.getMonth()+1).padStart(2,'0')}/${dt.getFullYear()}`;
  },
  'YYYY-MM-DD': (d) => {
    const dt = d instanceof Date ? d : new Date(d);
    return `${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`;
  },
};

// Maps currency label to symbol
export const CURRENCY_SYMBOL_MAP = {
  'USD ($)': '$',
  'EUR (€)': '€',
  'GBP (£)': '£',
  'NGN (₦)': '₦',
};

// UI string translations
export const TRANSLATIONS = {
  English: {
    // Nav
    dashboard: 'Dashboard', reportingPortal: 'Reporting Portal',
    financePortal: 'Finance Portal', analytics: 'Analytics',
    auditLogs: 'Audit Logs', userManagement: 'User Management',
    magazine: 'Magazine', notifications: 'Notifications', settings: 'Settings',
    // Welcome
    welcomeBack: 'Welcome back', today: 'Today',
    weeklyReminderTitle: 'Weekly Report Reminder',
    weeklyReminderDesc: "Don't forget to submit your weekly report by end of day Thursday.",
    // KPI
    totalReports: 'Total Reports', totalFinance: 'Total Finance',
    totalAttendance: 'Total Attendance', completionRate: 'Completion Rate',
    newMembers: 'New Members', avgAttendance: 'Avg. Attendance',
    // Table / actions
    recentActivity: 'Recent Activity', search: 'Search...',
    filters: 'Filters', showingReports: 'Showing', reports: 'reports',
    submitReport: 'Submit Report', addEntry: 'Add Entry',
    uploadCSV: 'Upload CSV/Excel', export: 'Export',
    view: 'View', download: 'Download', actions: 'Actions',
    status: 'Status', date: 'Date', region: 'Region', zone: 'Zone',
    campaign: 'Campaign', submittedBy: 'Submitted By', attendance: 'Attendance',
    notes: 'Notes', reportId: 'Report ID',
    // Finance
    totalRecords: 'Total Records', totalAmount: 'Total Amount',
    avgAmount: 'Average Amount', category: 'Category', amount: 'Amount',
    entryId: 'Entry ID',
    // Audit
    totalActivities: 'Total Activities', activeUsers: 'Active Users',
    modules: 'Modules', user: 'User', action: 'Action',
    module: 'Module', previousValue: 'Previous Value', updatedValue: 'Updated Value',
    timestamp: 'Timestamp',
    // Auth
    signOut: 'Sign Out', signIn: 'Sign In', signUp: 'Sign Up',
    email: 'Email', password: 'Password', fullName: 'Full Name',
    // Misc
    saveChanges: 'Save Changes', cancel: 'Cancel', close: 'Close',
    placeOrder: 'Place Order', backToOrders: 'Back to Orders',
    campaignPerformance: 'Campaign Performance',
    monthlyTrends: 'Monthly Trends', regionStats: 'Region-wise Statistics',
    analyticsDashboard: 'Analytics Dashboard',
    attendanceTrend: 'Attendance Trend', financeTrend: 'Finance Trend',
    regionalComparison: 'Regional Comparison', campaignDistribution: 'Campaign Distribution',
    attendanceSummary: 'Attendance Summary by Region', timeRange: 'Time Range',
    markAllRead: 'Mark All as Read',
    all: 'All', unread: 'Unread', new: 'New',
    noNotifications: 'No notifications', markAsRead: 'Mark as read',
    // Settings
    settingsTitle: 'Settings', settingsDesc: 'Manage your account preferences and configuration',
    profile: 'Profile', security: 'Security', preferences: 'Preferences', privacy: 'Privacy',
    profileInfo: 'Profile Information', profileInfoDesc: 'Update your personal details and contact information',
    firstName: 'First Name', lastName: 'Last Name', emailAddress: 'Email Address',
    phoneNumber: 'Phone Number', timezone: 'Timezone', role: 'Role', region: 'Region',
    changePhoto: 'Change Photo', remove: 'Remove',
    securityTitle: 'Security', securityDesc: 'Manage your password and account security',
    changePassword: 'Change Password', currentPassword: 'Current Password',
    newPassword: 'New Password', confirmPassword: 'Confirm Password',
    updatePassword: 'Update Password', twoFactor: 'Two-Factor Authentication',
    twoFactorDesc: 'Add an extra layer of security to your account.',
    enable2FA: 'Enable 2FA', enabled: 'Enabled', disabled: 'Disabled',
    activeSessions: 'Active Sessions', activeSessionsDesc: 'Devices currently signed into your account.',
    current: 'Current', revoke: 'Revoke',
    notifPrefs: 'Notification Preferences', notifPrefsDesc: 'Choose what you want to be notified about',
    savePreferences: 'Save Preferences',
    preferencesTitle: 'Preferences', preferencesDesc: 'Customize your platform experience',
    display: 'Display', language: 'Language', dateFormat: 'Date Format', currency: 'Currency',
    theme: 'Theme', themeDesc: 'Changes apply instantly across the entire app.',
    light: 'Light', dark: 'Dark', system: 'System',
    privacyTitle: 'Privacy', privacyDesc: 'Control your data and privacy settings',
    dataActivity: 'Data & Activity', dangerZone: 'Danger Zone',
    dangerZoneDesc: 'These actions are permanent and cannot be undone.',
    deleteAccount: 'Delete Account', deleteAccountDesc: 'Permanently delete your account and all associated data',
    activityLogging: 'Activity logging', activityLoggingDesc: 'Allow the platform to log your activity for audit purposes',
    analyticsTracking: 'Analytics tracking', analyticsTrackingDesc: 'Share anonymous usage data to help improve the platform',
    profileVisibility: 'Profile visibility', profileVisibilityDesc: 'Allow other users in your region to view your profile',
    financePortalTitle: 'Finance Portal', reportingPortalTitle: 'Reporting Portal',
    auditLogsTitle: 'Audit Logs',
  },

  French: {
    dashboard: 'Tableau de Bord', reportingPortal: 'Portail de Rapports',
    financePortal: 'Portail Financier', analytics: 'Analytique',
    auditLogs: "Journaux d'Audit", userManagement: 'Gestion des Utilisateurs',
    magazine: 'Magazine', notifications: 'Notifications', settings: 'Paramètres',
    welcomeBack: 'Bienvenue', today: "Aujourd'hui",
    weeklyReminderTitle: 'Rappel de Rapport Hebdomadaire',
    weeklyReminderDesc: "N'oubliez pas de soumettre votre rapport hebdomadaire avant jeudi.",
    totalReports: 'Total des Rapports', totalFinance: 'Total Financier',
    totalAttendance: 'Présence Totale', completionRate: "Taux d'Achèvement",
    newMembers: 'Nouveaux Membres', avgAttendance: 'Présence Moy.',
    recentActivity: 'Activité Récente', search: 'Rechercher...',
    filters: 'Filtres', showingReports: 'Affichage de', reports: 'rapports',
    submitReport: 'Soumettre le Rapport', addEntry: 'Ajouter une Entrée',
    uploadCSV: 'Télécharger CSV/Excel', export: 'Exporter',
    view: 'Voir', download: 'Télécharger', actions: 'Actions',
    status: 'Statut', date: 'Date', region: 'Région', zone: 'Zone',
    campaign: 'Campagne', submittedBy: 'Soumis Par', attendance: 'Présence',
    notes: 'Notes', reportId: 'ID Rapport',
    totalRecords: 'Total des Enregistrements', totalAmount: 'Montant Total',
    avgAmount: 'Montant Moyen', category: 'Catégorie', amount: 'Montant',
    entryId: 'ID Entrée',
    totalActivities: 'Total des Activités', activeUsers: 'Utilisateurs Actifs',
    modules: 'Modules', user: 'Utilisateur', action: 'Action',
    module: 'Module', previousValue: 'Valeur Précédente', updatedValue: 'Valeur Mise à Jour',
    timestamp: 'Horodatage',
    signOut: 'Se Déconnecter', signIn: 'Se Connecter', signUp: "S'inscrire",
    email: 'E-mail', password: 'Mot de passe', fullName: 'Nom Complet',
    saveChanges: 'Enregistrer', cancel: 'Annuler', close: 'Fermer',
    placeOrder: 'Passer Commande', backToOrders: 'Retour aux Commandes',
    campaignPerformance: 'Performance des Campagnes',
    monthlyTrends: 'Tendances Mensuelles', regionStats: 'Statistiques Régionales',
    analyticsDashboard: 'Tableau Analytique',
    attendanceTrend: 'Tendance de Présence', financeTrend: 'Tendance Financière',
    regionalComparison: 'Comparaison Régionale', campaignDistribution: 'Distribution des Campagnes',
    attendanceSummary: 'Résumé de Présence par Région', timeRange: 'Période',
    markAllRead: 'Tout Marquer comme Lu',
    all: 'Tout', unread: 'Non lu', new: 'Nouveau',
    noNotifications: 'Aucune notification', markAsRead: 'Marquer comme lu',
    settingsTitle: 'Paramètres', settingsDesc: 'Gérez vos préférences et configuration',
    profile: 'Profil', security: 'Sécurité', preferences: 'Préférences', privacy: 'Confidentialité',
    profileInfo: 'Informations du Profil', profileInfoDesc: 'Mettez à jour vos coordonnées',
    firstName: 'Prénom', lastName: 'Nom de Famille', emailAddress: 'Adresse E-mail',
    phoneNumber: 'Numéro de Téléphone', timezone: 'Fuseau Horaire', role: 'Rôle', region: 'Région',
    changePhoto: 'Changer la Photo', remove: 'Supprimer',
    securityTitle: 'Sécurité', securityDesc: 'Gérez votre mot de passe et la sécurité',
    changePassword: 'Changer le Mot de Passe', currentPassword: 'Mot de Passe Actuel',
    newPassword: 'Nouveau Mot de Passe', confirmPassword: 'Confirmer le Mot de Passe',
    updatePassword: 'Mettre à Jour le Mot de Passe', twoFactor: 'Authentification à Deux Facteurs',
    twoFactorDesc: 'Ajoutez une couche de sécurité supplémentaire.',
    enable2FA: 'Activer 2FA', enabled: 'Activé', disabled: 'Désactivé',
    activeSessions: 'Sessions Actives', activeSessionsDesc: 'Appareils connectés à votre compte.',
    current: 'Actuel', revoke: 'Révoquer',
    notifPrefs: 'Préférences de Notification', notifPrefsDesc: 'Choisissez ce dont vous voulez être notifié',
    savePreferences: 'Enregistrer les Préférences',
    preferencesTitle: 'Préférences', preferencesDesc: 'Personnalisez votre expérience',
    display: 'Affichage', language: 'Langue', dateFormat: 'Format de Date', currency: 'Devise',
    theme: 'Thème', themeDesc: "Les changements s'appliquent instantanément.",
    light: 'Clair', dark: 'Sombre', system: 'Système',
    privacyTitle: 'Confidentialité', privacyDesc: 'Contrôlez vos données et paramètres de confidentialité',
    dataActivity: 'Données et Activité', dangerZone: 'Zone Dangereuse',
    dangerZoneDesc: 'Ces actions sont permanentes et irréversibles.',
    deleteAccount: 'Supprimer le Compte', deleteAccountDesc: 'Supprimez définitivement votre compte',
    activityLogging: "Journal d'activité", activityLoggingDesc: 'Permettre à la plateforme de journaliser votre activité',
    analyticsTracking: 'Suivi analytique', analyticsTrackingDesc: "Partager des données d'utilisation anonymes",
    profileVisibility: 'Visibilité du profil', profileVisibilityDesc: 'Permettre aux autres utilisateurs de voir votre profil',
    financePortalTitle: 'Portail Financier', reportingPortalTitle: 'Portail de Rapports',
    auditLogsTitle: "Journaux d'Audit",
  },

  Spanish: {
    dashboard: 'Panel Principal', reportingPortal: 'Portal de Informes',
    financePortal: 'Portal Financiero', analytics: 'Análisis',
    auditLogs: 'Registros de Auditoría', userManagement: 'Gestión de Usuarios',
    magazine: 'Revista', notifications: 'Notificaciones', settings: 'Configuración',
    welcomeBack: 'Bienvenido de nuevo', today: 'Hoy',
    weeklyReminderTitle: 'Recordatorio de Informe Semanal',
    weeklyReminderDesc: 'No olvides enviar tu informe semanal antes del jueves.',
    totalReports: 'Total de Informes', totalFinance: 'Total Financiero',
    totalAttendance: 'Asistencia Total', completionRate: 'Tasa de Finalización',
    newMembers: 'Nuevos Miembros', avgAttendance: 'Asistencia Prom.',
    recentActivity: 'Actividad Reciente', search: 'Buscar...',
    filters: 'Filtros', showingReports: 'Mostrando', reports: 'informes',
    submitReport: 'Enviar Informe', addEntry: 'Agregar Entrada',
    uploadCSV: 'Subir CSV/Excel', export: 'Exportar',
    view: 'Ver', download: 'Descargar', actions: 'Acciones',
    status: 'Estado', date: 'Fecha', region: 'Región', zone: 'Zona',
    campaign: 'Campaña', submittedBy: 'Enviado Por', attendance: 'Asistencia',
    notes: 'Notas', reportId: 'ID Informe',
    totalRecords: 'Total de Registros', totalAmount: 'Monto Total',
    avgAmount: 'Monto Promedio', category: 'Categoría', amount: 'Monto',
    entryId: 'ID Entrada',
    totalActivities: 'Total de Actividades', activeUsers: 'Usuarios Activos',
    modules: 'Módulos', user: 'Usuario', action: 'Acción',
    module: 'Módulo', previousValue: 'Valor Anterior', updatedValue: 'Valor Actualizado',
    timestamp: 'Marca de Tiempo',
    signOut: 'Cerrar Sesión', signIn: 'Iniciar Sesión', signUp: 'Registrarse',
    email: 'Correo', password: 'Contraseña', fullName: 'Nombre Completo',
    saveChanges: 'Guardar Cambios', cancel: 'Cancelar', close: 'Cerrar',
    placeOrder: 'Realizar Pedido', backToOrders: 'Volver a Pedidos',
    campaignPerformance: 'Rendimiento de Campañas',
    monthlyTrends: 'Tendencias Mensuales', regionStats: 'Estadísticas Regionales',
    analyticsDashboard: 'Panel Analítico',
    attendanceTrend: 'Tendencia de Asistencia', financeTrend: 'Tendencia Financiera',
    regionalComparison: 'Comparación Regional', campaignDistribution: 'Distribución de Campañas',
    attendanceSummary: 'Resumen de Asistencia por Región', timeRange: 'Período',
    markAllRead: 'Marcar Todo como Leído',
    all: 'Todo', unread: 'No leído', new: 'Nuevo',
    noNotifications: 'Sin notificaciones', markAsRead: 'Marcar como leído',
    settingsTitle: 'Configuración', settingsDesc: 'Administra tus preferencias y configuración',
    profile: 'Perfil', security: 'Seguridad', preferences: 'Preferencias', privacy: 'Privacidad',
    profileInfo: 'Información del Perfil', profileInfoDesc: 'Actualiza tus datos personales',
    firstName: 'Nombre', lastName: 'Apellido', emailAddress: 'Correo Electrónico',
    phoneNumber: 'Número de Teléfono', timezone: 'Zona Horaria', role: 'Rol', region: 'Región',
    changePhoto: 'Cambiar Foto', remove: 'Eliminar',
    securityTitle: 'Seguridad', securityDesc: 'Administra tu contraseña y seguridad',
    changePassword: 'Cambiar Contraseña', currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña', confirmPassword: 'Confirmar Contraseña',
    updatePassword: 'Actualizar Contraseña', twoFactor: 'Autenticación de Dos Factores',
    twoFactorDesc: 'Añade una capa extra de seguridad.',
    enable2FA: 'Activar 2FA', enabled: 'Activado', disabled: 'Desactivado',
    activeSessions: 'Sesiones Activas', activeSessionsDesc: 'Dispositivos conectados a tu cuenta.',
    current: 'Actual', revoke: 'Revocar',
    notifPrefs: 'Preferencias de Notificación', notifPrefsDesc: 'Elige sobre qué quieres ser notificado',
    savePreferences: 'Guardar Preferencias',
    preferencesTitle: 'Preferencias', preferencesDesc: 'Personaliza tu experiencia',
    display: 'Pantalla', language: 'Idioma', dateFormat: 'Formato de Fecha', currency: 'Moneda',
    theme: 'Tema', themeDesc: 'Los cambios se aplican instantáneamente.',
    light: 'Claro', dark: 'Oscuro', system: 'Sistema',
    privacyTitle: 'Privacidad', privacyDesc: 'Controla tus datos y configuración de privacidad',
    dataActivity: 'Datos y Actividad', dangerZone: 'Zona de Peligro',
    dangerZoneDesc: 'Estas acciones son permanentes e irreversibles.',
    deleteAccount: 'Eliminar Cuenta', deleteAccountDesc: 'Elimina permanentemente tu cuenta',
    activityLogging: 'Registro de actividad', activityLoggingDesc: 'Permitir que la plataforma registre tu actividad',
    analyticsTracking: 'Seguimiento analítico', analyticsTrackingDesc: 'Compartir datos de uso anónimos',
    profileVisibility: 'Visibilidad del perfil', profileVisibilityDesc: 'Permitir que otros usuarios vean tu perfil',
    financePortalTitle: 'Portal Financiero', reportingPortalTitle: 'Portal de Informes',
    auditLogsTitle: 'Registros de Auditoría',
  },

  Portuguese: {
    dashboard: 'Painel', reportingPortal: 'Portal de Relatórios',
    financePortal: 'Portal Financeiro', analytics: 'Análises',
    auditLogs: 'Registros de Auditoria', userManagement: 'Gestão de Usuários',
    magazine: 'Revista', notifications: 'Notificações', settings: 'Configurações',
    welcomeBack: 'Bem-vindo de volta', today: 'Hoje',
    weeklyReminderTitle: 'Lembrete de Relatório Semanal',
    weeklyReminderDesc: 'Não se esqueça de enviar seu relatório semanal até quinta-feira.',
    totalReports: 'Total de Relatórios', totalFinance: 'Total Financeiro',
    totalAttendance: 'Presença Total', completionRate: 'Taxa de Conclusão',
    newMembers: 'Novos Membros', avgAttendance: 'Presença Méd.',
    recentActivity: 'Atividade Recente', search: 'Pesquisar...',
    filters: 'Filtros', showingReports: 'Mostrando', reports: 'relatórios',
    submitReport: 'Enviar Relatório', addEntry: 'Adicionar Entrada',
    uploadCSV: 'Carregar CSV/Excel', export: 'Exportar',
    view: 'Ver', download: 'Baixar', actions: 'Ações',
    status: 'Status', date: 'Data', region: 'Região', zone: 'Zona',
    campaign: 'Campanha', submittedBy: 'Enviado Por', attendance: 'Presença',
    notes: 'Notas', reportId: 'ID Relatório',
    totalRecords: 'Total de Registros', totalAmount: 'Valor Total',
    avgAmount: 'Valor Médio', category: 'Categoria', amount: 'Valor',
    entryId: 'ID Entrada',
    totalActivities: 'Total de Atividades', activeUsers: 'Usuários Ativos',
    modules: 'Módulos', user: 'Usuário', action: 'Ação',
    module: 'Módulo', previousValue: 'Valor Anterior', updatedValue: 'Valor Atualizado',
    timestamp: 'Carimbo de Tempo',
    signOut: 'Sair', signIn: 'Entrar', signUp: 'Cadastrar',
    email: 'E-mail', password: 'Senha', fullName: 'Nome Completo',
    saveChanges: 'Salvar Alterações', cancel: 'Cancelar', close: 'Fechar',
    placeOrder: 'Fazer Pedido', backToOrders: 'Voltar aos Pedidos',
    campaignPerformance: 'Desempenho de Campanhas',
    monthlyTrends: 'Tendências Mensais', regionStats: 'Estatísticas Regionais',
    analyticsDashboard: 'Painel Analítico',
    attendanceTrend: 'Tendência de Presença', financeTrend: 'Tendência Financeira',
    regionalComparison: 'Comparação Regional', campaignDistribution: 'Distribuição de Campanhas',
    attendanceSummary: 'Resumo de Presença por Região', timeRange: 'Período',
    markAllRead: 'Marcar Tudo como Lido',
    all: 'Tudo', unread: 'Não lido', new: 'Novo',
    noNotifications: 'Sem notificações', markAsRead: 'Marcar como lido',
    settingsTitle: 'Configurações', settingsDesc: 'Gerencie suas preferências e configuração',
    profile: 'Perfil', security: 'Segurança', preferences: 'Preferências', privacy: 'Privacidade',
    profileInfo: 'Informações do Perfil', profileInfoDesc: 'Atualize seus dados pessoais',
    firstName: 'Nome', lastName: 'Sobrenome', emailAddress: 'Endereço de E-mail',
    phoneNumber: 'Número de Telefone', timezone: 'Fuso Horário', role: 'Função', region: 'Região',
    changePhoto: 'Alterar Foto', remove: 'Remover',
    securityTitle: 'Segurança', securityDesc: 'Gerencie sua senha e segurança',
    changePassword: 'Alterar Senha', currentPassword: 'Senha Atual',
    newPassword: 'Nova Senha', confirmPassword: 'Confirmar Senha',
    updatePassword: 'Atualizar Senha', twoFactor: 'Autenticação de Dois Fatores',
    twoFactorDesc: 'Adicione uma camada extra de segurança.',
    enable2FA: 'Ativar 2FA', enabled: 'Ativado', disabled: 'Desativado',
    activeSessions: 'Sessões Ativas', activeSessionsDesc: 'Dispositivos conectados à sua conta.',
    current: 'Atual', revoke: 'Revogar',
    notifPrefs: 'Preferências de Notificação', notifPrefsDesc: 'Escolha sobre o que deseja ser notificado',
    savePreferences: 'Salvar Preferências',
    preferencesTitle: 'Preferências', preferencesDesc: 'Personalize sua experiência',
    display: 'Exibição', language: 'Idioma', dateFormat: 'Formato de Data', currency: 'Moeda',
    theme: 'Tema', themeDesc: 'As alterações se aplicam instantaneamente.',
    light: 'Claro', dark: 'Escuro', system: 'Sistema',
    privacyTitle: 'Privacidade', privacyDesc: 'Controle seus dados e configurações de privacidade',
    dataActivity: 'Dados e Atividade', dangerZone: 'Zona de Perigo',
    dangerZoneDesc: 'Essas ações são permanentes e irreversíveis.',
    deleteAccount: 'Excluir Conta', deleteAccountDesc: 'Exclua permanentemente sua conta',
    activityLogging: 'Registro de atividade', activityLoggingDesc: 'Permitir que a plataforma registre sua atividade',
    analyticsTracking: 'Rastreamento analítico', analyticsTrackingDesc: 'Compartilhar dados de uso anônimos',
    profileVisibility: 'Visibilidade do perfil', profileVisibilityDesc: 'Permitir que outros usuários vejam seu perfil',
    financePortalTitle: 'Portal Financeiro', reportingPortalTitle: 'Portal de Relatórios',
    auditLogsTitle: 'Registros de Auditoria',
  },

  Yoruba: {
    dashboard: 'Dáṣíbọ́ọ̀dù', reportingPortal: 'Ẹ̀bùn Ìjábọ̀',
    financePortal: 'Ẹ̀bùn Ìṣúná', analytics: 'Ìtúpalẹ̀',
    auditLogs: 'Àkọsílẹ̀ Àyẹ̀wò', userManagement: 'Ìṣàkóso Olùmúlò',
    magazine: 'Ìwé Ìròyìn', notifications: 'Ìfitónilétí', settings: 'Ìtòlẹ́sẹẹsẹ',
    welcomeBack: 'Ẹ káàbọ̀', today: 'Òní',
    weeklyReminderTitle: 'Ìránlétí Ìjábọ̀ Ọ̀sẹ̀',
    weeklyReminderDesc: 'Má gbàgbé láti fi ìjábọ̀ rẹ sílẹ̀ ṣáájú ọjọ́ Ẹtì.',
    totalReports: 'Àpapọ̀ Ìjábọ̀', totalFinance: 'Àpapọ̀ Ìṣúná',
    totalAttendance: 'Àpapọ̀ Ìjókòó', completionRate: 'Ìpele Ìparí',
    newMembers: 'Àwọn Ọmọ Tuntun', avgAttendance: 'Ìjókòó Àárọ̀',
    recentActivity: 'Ìgbésẹ̀ Àìpẹ́', search: 'Wá...',
    filters: 'Àṣàyàn', showingReports: 'Ìfihàn', reports: 'ìjábọ̀',
    submitReport: 'Fi Ìjábọ̀ Sílẹ̀', addEntry: 'Ṣàfikún Ìforúkọsílẹ̀',
    uploadCSV: 'Gbé CSV/Excel Sórí', export: 'Gbé Jáde',
    view: 'Wò', download: 'Gba', actions: 'Ìgbésẹ̀',
    status: 'Ipò', date: 'Ọjọ́', region: 'Àgbègbè', zone: 'Àgbègbè Kékeré',
    campaign: 'Ìpolongo', submittedBy: 'Tí a Fi Sílẹ̀ Látọwọ́', attendance: 'Ìjókòó',
    notes: 'Àkọsílẹ̀', reportId: 'Nọ́mbà Ìjábọ̀',
    totalRecords: 'Àpapọ̀ Àkọsílẹ̀', totalAmount: 'Àpapọ̀ Owó',
    avgAmount: 'Owó Àárọ̀', category: 'Ẹ̀ka', amount: 'Owó',
    entryId: 'Nọ́mbà Ìforúkọsílẹ̀',
    totalActivities: 'Àpapọ̀ Ìgbésẹ̀', activeUsers: 'Àwọn Olùmúlò Tó Ń Ṣiṣẹ́',
    modules: 'Àwọn Ẹ̀ka', user: 'Olùmúlò', action: 'Ìgbésẹ̀',
    module: 'Ẹ̀ka', previousValue: 'Iye Tẹ́lẹ̀', updatedValue: 'Iye Tuntun',
    timestamp: 'Àkókò',
    signOut: 'Jáde', signIn: 'Wọlé', signUp: 'Forúkọsílẹ̀',
    email: 'Ímeèlì', password: 'Ọ̀rọ̀ Aṣínà', fullName: 'Orúkọ Kíkún',
    saveChanges: 'Tọ́jú Àyípadà', cancel: 'Fagilé', close: 'Pa',
    placeOrder: 'Ṣe Àṣẹ', backToOrders: 'Padà sí Àwọn Àṣẹ',
    campaignPerformance: 'Ìṣẹ́ Ìpolongo',
    monthlyTrends: 'Ìṣòro Oṣooṣù', regionStats: 'Ìṣirò Àgbègbè',
    analyticsDashboard: 'Dáṣíbọ́ọ̀dù Ìtúpalẹ̀',
    attendanceTrend: 'Ìṣòro Ìjókòó', financeTrend: 'Ìṣòro Ìṣúná',
    regionalComparison: 'Ìfiwéra Àgbègbè', campaignDistribution: 'Ìpínpín Ìpolongo',
    attendanceSummary: 'Àkópọ̀ Ìjókòó Látọwọ́ Àgbègbè', timeRange: 'Àkókò',
    markAllRead: 'Samisi Gbogbo Gẹ́gẹ́ bí a ti Kà',
    all: 'Gbogbo', unread: 'Ti a Kò Kà', new: 'Tuntun',
    noNotifications: 'Kò sí Ìfitónilétí', markAsRead: 'Samisi Gẹ́gẹ́ bí a ti Kà',
    settingsTitle: 'Ìtòlẹ́sẹẹsẹ', settingsDesc: 'Saré àwọn ìfẹ́ rẹ àti ìtò rẹ',
    profile: 'Ìwọ̀ Araọn', security: 'Àbò', preferences: 'Ìfẹ́ Araọn', privacy: 'Àṣírì',
    profileInfo: 'Ìtọmọ Ìwọ̀ Araọn', profileInfoDesc: 'Mọ ìtọmọ araọn rẹ ṣínsin',
    firstName: 'Orúkọ Àkọ́kọ́', lastName: 'Orúkọ Idí', emailAddress: 'Àdírèsì Ímeèlì',
    phoneNumber: 'Nọ́mbà Fónù', timezone: 'Àkókò Àgbègbè', role: 'Ọ̀nà', region: 'Àgbègbè',
    changePhoto: 'Yi Awọ̀ràn Pàdà', remove: 'Yọ̀ Kú̀',
    securityTitle: 'Àbò', securityDesc: 'Saré ọ̀rọ̀ aṣínà rẹ àti àbò',
    changePassword: 'Yi Ọ̀rọ̀ Aṣínà Pàdà', currentPassword: 'Ọ̀rọ̀ Aṣínà Télẹ̀',
    newPassword: 'Ọ̀rọ̀ Aṣínà Tuntun', confirmPassword: 'Jẹ́rẹ̀ Ọ̀rọ̀ Aṣínà',
    updatePassword: 'Mọ Ọ̀rọ̀ Aṣínà Ṣínsin', twoFactor: 'Àmòjú-Èjò Ìjẹ́ríisi',
    twoFactorDesc: 'Fi àbò àárọ̀ kun sí àkóóùnù rẹ.',
    enable2FA: 'Mu 2FA Ṣiṣẹ́', enabled: 'Ti Mu Ṣiṣẹ́', disabled: 'Ti Pa',
    activeSessions: 'Àwọn Ìpade Tó Ń Ṣiṣẹ́', activeSessionsDesc: 'Àwọn ìrò tó wọlé sí àkóùnù rẹ.',
    current: 'Tó Wa', revoke: 'Fágilé',
    notifPrefs: 'Ìfẹ́ Ìfitónilétí', notifPrefsDesc: 'Yàn ohun tó fẹ́ jẹ́ kí a fi tónilétí rẹ',
    savePreferences: 'Tọ́jú Ìfẹ́',
    preferencesTitle: 'Ìfẹ́ Araọn', preferencesDesc: 'Saré ìríà rẹ lárí ìlànà rẹ',
    display: 'Ìfihàn', language: 'Èdè', dateFormat: 'Àrútó Ọjọ́', currency: 'Owó Orílẹ̀èdè',
    theme: 'Àrútó Ìwọ̀', themeDesc: 'Àyípadà mà waye lẹ́sẹ̀kẹ́sẹ̀.',
    light: 'Àìmọ̀lé', dark: 'Òkùtù', system: 'Èrò Nàà',
    privacyTitle: 'Àṣírì', privacyDesc: 'Saré àwọn data rẹ àti àṣírì',
    dataActivity: 'Data àti Ìgbésẹ̀', dangerZone: 'Àgbègbè Îwú',
    dangerZoneDesc: 'Àwọn ìgbésẹ̀ wọ̀nyí jẹ́ dédé kó sí àṣé ìpadà.',
    deleteAccount: 'Pa Àkóùnù Rẹ̀', deleteAccountDesc: 'Pa àkóùnù rẹ ré máá láérí',
    activityLogging: 'Ìgbànà Ìgbésẹ̀', activityLoggingDesc: 'Jekí ìlànà gba ìgbésẹ̀ rẹ sílẹ̀',
    analyticsTracking: 'Ìtúàṣẹ̀ Ìtúpalẹ̀', analyticsTrackingDesc: 'Pin data líàṣé láti ran lọ́wọ́ láti mọ ìlànà dárá',
    profileVisibility: 'Ìfihàn Ìwọ̀ Araọn', profileVisibilityDesc: 'Jekí àwọn olùmúlò míràn wo ìwọ̀ araọn rẹ',
    financePortalTitle: 'Ẹ̀bùn Ìṣúná', reportingPortalTitle: 'Ẹ̀bùn Ìjábọ̀',
    auditLogsTitle: 'Àkọsílẹ̀ Àyẹ̀wò',
  },

  // ─── NEW: Hindi ───────────────────────────────────────────────────────────
  Hindi: {
    dashboard: 'डैशबोर्ड', reportingPortal: 'रिपोर्टिंग पोर्टल',
    financePortal: 'वित्त पोर्टल', analytics: 'विश्लेषण',
    auditLogs: 'ऑडिट लॉग', userManagement: 'उपयोगकर्ता प्रबंधन',
    magazine: 'पत्रिका', notifications: 'सूचनाएँ', settings: 'सेटिंग्स',
    welcomeBack: 'वापस स्वागत है', today: 'आज',
    weeklyReminderTitle: 'साप्ताहिक रिपोर्ट अनुस्मारक',
    weeklyReminderDesc: 'गुरुवार के अंत तक अपनी साप्ताहिक रिपोर्ट जमा करना न भूलें।',
    totalReports: 'कुल रिपोर्ट', totalFinance: 'कुल वित्त',
    totalAttendance: 'कुल उपस्थिति', completionRate: 'पूर्णता दर',
    newMembers: 'नए सदस्य', avgAttendance: 'औसत उपस्थिति',
    recentActivity: 'हालिया गतिविधि', search: 'खोजें...',
    filters: 'फ़िल्टर', showingReports: 'दिखाया जा रहा है', reports: 'रिपोर्ट',
    submitReport: 'रिपोर्ट सबमिट करें', addEntry: 'प्रविष्टि जोड़ें',
    uploadCSV: 'CSV/Excel अपलोड करें', export: 'निर्यात करें',
    view: 'देखें', download: 'डाउनलोड', actions: 'क्रियाएँ',
    status: 'स्थिति', date: 'तारीख', region: 'क्षेत्र', zone: 'ज़ोन',
    campaign: 'अभियान', submittedBy: 'द्वारा सबमिट', attendance: 'उपस्थिति',
    notes: 'नोट्स', reportId: 'रिपोर्ट आईडी',
    totalRecords: 'कुल रिकॉर्ड', totalAmount: 'कुल राशि',
    avgAmount: 'औसत राशि', category: 'श्रेणी', amount: 'राशि',
    entryId: 'प्रविष्टि आईडी',
    totalActivities: 'कुल गतिविधियाँ', activeUsers: 'सक्रिय उपयोगकर्ता',
    modules: 'मॉड्यूल', user: 'उपयोगकर्ता', action: 'क्रिया',
    module: 'मॉड्यूल', previousValue: 'पिछला मान', updatedValue: 'अपडेटेड मान',
    timestamp: 'टाइमस्टैम्प',
    signOut: 'साइन आउट', signIn: 'साइन इन', signUp: 'साइन अप',
    email: 'ईमेल', password: 'पासवर्ड', fullName: 'पूरा नाम',
    saveChanges: 'बदलाव सहेजें', cancel: 'रद्द करें', close: 'बंद करें',
    placeOrder: 'ऑर्डर दें', backToOrders: 'ऑर्डर पर वापस जाएँ',
    campaignPerformance: 'अभियान प्रदर्शन',
    monthlyTrends: 'मासिक रुझान', regionStats: 'क्षेत्रवार आँकड़े',
    analyticsDashboard: 'विश्लेषण डैशबोर्ड',
    attendanceTrend: 'उपस्थिति रुझान', financeTrend: 'वित्त रुझान',
    regionalComparison: 'क्षेत्रीय तुलना', campaignDistribution: 'अभियान वितरण',
    attendanceSummary: 'क्षेत्रानुसार उपस्थिति सारांश', timeRange: 'समय सीमा',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    all: 'सभी', unread: 'अपठित', new: 'नया',
    noNotifications: 'कोई सूचना नहीं', markAsRead: 'पढ़ा हुआ चिह्नित करें',
    settingsTitle: 'सेटिंग्स', settingsDesc: 'अपनी खाता प्राथमिकताएँ और कॉन्फ़िगरेशन प्रबंधित करें',
    profile: 'प्रोफ़ाइल', security: 'सुरक्षा', preferences: 'प्राथमिकताएँ', privacy: 'गोपनीयता',
    profileInfo: 'प्रोफ़ाइल जानकारी', profileInfoDesc: 'अपना व्यक्तिगत विवरण अपडेट करें',
    firstName: 'पहला नाम', lastName: 'अंतिम नाम', emailAddress: 'ईमेल पता',
    phoneNumber: 'फ़ोन नंबर', timezone: 'टाइमज़ोन', role: 'भूमिका', region: 'क्षेत्र',
    changePhoto: 'फ़ोटो बदलें', remove: 'हटाएँ',
    securityTitle: 'सुरक्षा', securityDesc: 'अपना पासवर्ड और खाता सुरक्षा प्रबंधित करें',
    changePassword: 'पासवर्ड बदलें', currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड', confirmPassword: 'पासवर्ड की पुष्टि करें',
    updatePassword: 'पासवर्ड अपडेट करें', twoFactor: 'दो-कारक प्रमाणीकरण',
    twoFactorDesc: 'अपने खाते में सुरक्षा की एक अतिरिक्त परत जोड़ें।',
    enable2FA: '2FA सक्षम करें', enabled: 'सक्षम', disabled: 'अक्षम',
    activeSessions: 'सक्रिय सत्र', activeSessionsDesc: 'वर्तमान में आपके खाते में लॉग इन डिवाइस।',
    current: 'वर्तमान', revoke: 'रद्द करें',
    notifPrefs: 'सूचना प्राथमिकताएँ', notifPrefsDesc: 'चुनें कि आप क्या सूचनाएँ प्राप्त करना चाहते हैं',
    savePreferences: 'प्राथमिकताएँ सहेजें',
    preferencesTitle: 'प्राथमिकताएँ', preferencesDesc: 'अपना प्लेटफ़ॉर्म अनुभव अनुकूलित करें',
    display: 'प्रदर्शन', language: 'भाषा', dateFormat: 'तारीख प्रारूप', currency: 'मुद्रा',
    theme: 'थीम', themeDesc: 'परिवर्तन पूरे ऐप पर तुरंत लागू होते हैं।',
    light: 'हल्का', dark: 'गहरा', system: 'सिस्टम',
    privacyTitle: 'गोपनीयता', privacyDesc: 'अपना डेटा और गोपनीयता सेटिंग्स नियंत्रित करें',
    dataActivity: 'डेटा और गतिविधि', dangerZone: 'खतरनाक क्षेत्र',
    dangerZoneDesc: 'ये क्रियाएँ स्थायी हैं और इन्हें पूर्ववत नहीं किया जा सकता।',
    deleteAccount: 'खाता हटाएँ', deleteAccountDesc: 'अपना खाता और सभी संबंधित डेटा स्थायी रूप से हटाएँ',
    activityLogging: 'गतिविधि लॉगिंग', activityLoggingDesc: 'ऑडिट के लिए प्लेटफ़ॉर्म को आपकी गतिविधि लॉग करने दें',
    analyticsTracking: 'विश्लेषण ट्रैकिंग', analyticsTrackingDesc: 'प्लेटफ़ॉर्म को बेहतर बनाने के लिए अज्ञात उपयोग डेटा साझा करें',
    profileVisibility: 'प्रोफ़ाइल दृश्यता', profileVisibilityDesc: 'अपने क्षेत्र के अन्य उपयोगकर्ताओं को अपनी प्रोफ़ाइल देखने दें',
    financePortalTitle: 'वित्त पोर्टल', reportingPortalTitle: 'रिपोर्टिंग पोर्टल',
    auditLogsTitle: 'ऑडिट लॉग',
  },

  // ─── NEW: Russian ─────────────────────────────────────────────────────────
  Russian: {
    dashboard: 'Панель управления', reportingPortal: 'Портал отчётов',
    financePortal: 'Финансовый портал', analytics: 'Аналитика',
    auditLogs: 'Журналы аудита', userManagement: 'Управление пользователями',
    magazine: 'Журнал', notifications: 'Уведомления', settings: 'Настройки',
    welcomeBack: 'С возвращением', today: 'Сегодня',
    weeklyReminderTitle: 'Напоминание о еженедельном отчёте',
    weeklyReminderDesc: 'Не забудьте отправить еженедельный отчёт до конца четверга.',
    totalReports: 'Всего отчётов', totalFinance: 'Итого финансов',
    totalAttendance: 'Общая посещаемость', completionRate: 'Уровень выполнения',
    newMembers: 'Новые участники', avgAttendance: 'Ср. посещаемость',
    recentActivity: 'Последние действия', search: 'Поиск...',
    filters: 'Фильтры', showingReports: 'Показано', reports: 'отчётов',
    submitReport: 'Отправить отчёт', addEntry: 'Добавить запись',
    uploadCSV: 'Загрузить CSV/Excel', export: 'Экспорт',
    view: 'Просмотр', download: 'Скачать', actions: 'Действия',
    status: 'Статус', date: 'Дата', region: 'Регион', zone: 'Зона',
    campaign: 'Кампания', submittedBy: 'Отправлено', attendance: 'Посещаемость',
    notes: 'Заметки', reportId: 'ID отчёта',
    totalRecords: 'Всего записей', totalAmount: 'Общая сумма',
    avgAmount: 'Средняя сумма', category: 'Категория', amount: 'Сумма',
    entryId: 'ID записи',
    totalActivities: 'Всего активностей', activeUsers: 'Активные пользователи',
    modules: 'Модули', user: 'Пользователь', action: 'Действие',
    module: 'Модуль', previousValue: 'Предыдущее значение', updatedValue: 'Обновлённое значение',
    timestamp: 'Временная метка',
    signOut: 'Выйти', signIn: 'Войти', signUp: 'Зарегистрироваться',
    email: 'Эл. почта', password: 'Пароль', fullName: 'Полное имя',
    saveChanges: 'Сохранить изменения', cancel: 'Отмена', close: 'Закрыть',
    placeOrder: 'Оформить заказ', backToOrders: 'Назад к заказам',
    campaignPerformance: 'Эффективность кампаний',
    monthlyTrends: 'Ежемесячные тенденции', regionStats: 'Региональная статистика',
    analyticsDashboard: 'Аналитическая панель',
    attendanceTrend: 'Тенденция посещаемости', financeTrend: 'Финансовая тенденция',
    regionalComparison: 'Региональное сравнение', campaignDistribution: 'Распределение кампаний',
    attendanceSummary: 'Сводка посещаемости по регионам', timeRange: 'Временной диапазон',
    markAllRead: 'Отметить все как прочитанные',
    all: 'Все', unread: 'Непрочитанные', new: 'Новое',
    noNotifications: 'Нет уведомлений', markAsRead: 'Отметить как прочитанное',
    settingsTitle: 'Настройки', settingsDesc: 'Управляйте настройками и конфигурацией аккаунта',
    profile: 'Профиль', security: 'Безопасность', preferences: 'Предпочтения', privacy: 'Конфиденциальность',
    profileInfo: 'Информация профиля', profileInfoDesc: 'Обновите личные данные и контактную информацию',
    firstName: 'Имя', lastName: 'Фамилия', emailAddress: 'Адрес эл. почты',
    phoneNumber: 'Номер телефона', timezone: 'Часовой пояс', role: 'Роль', region: 'Регион',
    changePhoto: 'Изменить фото', remove: 'Удалить',
    securityTitle: 'Безопасность', securityDesc: 'Управляйте паролем и безопасностью аккаунта',
    changePassword: 'Изменить пароль', currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль', confirmPassword: 'Подтвердить пароль',
    updatePassword: 'Обновить пароль', twoFactor: 'Двухфакторная аутентификация',
    twoFactorDesc: 'Добавьте дополнительный уровень защиты для аккаунта.',
    enable2FA: 'Включить 2FA', enabled: 'Включено', disabled: 'Отключено',
    activeSessions: 'Активные сессии', activeSessionsDesc: 'Устройства, вошедшие в ваш аккаунт.',
    current: 'Текущий', revoke: 'Отозвать',
    notifPrefs: 'Настройки уведомлений', notifPrefsDesc: 'Выберите, о чём хотите получать уведомления',
    savePreferences: 'Сохранить предпочтения',
    preferencesTitle: 'Предпочтения', preferencesDesc: 'Настройте интерфейс платформы',
    display: 'Отображение', language: 'Язык', dateFormat: 'Формат даты', currency: 'Валюта',
    theme: 'Тема', themeDesc: 'Изменения применяются мгновенно во всём приложении.',
    light: 'Светлая', dark: 'Тёмная', system: 'Системная',
    privacyTitle: 'Конфиденциальность', privacyDesc: 'Управляйте данными и настройками конфиденциальности',
    dataActivity: 'Данные и активность', dangerZone: 'Опасная зона',
    dangerZoneDesc: 'Эти действия необратимы.',
    deleteAccount: 'Удалить аккаунт', deleteAccountDesc: 'Безвозвратно удалить аккаунт и все связанные данные',
    activityLogging: 'Ведение журнала активности', activityLoggingDesc: 'Разрешить платформе записывать вашу активность для аудита',
    analyticsTracking: 'Аналитическое отслеживание', analyticsTrackingDesc: 'Делиться анонимными данными для улучшения платформы',
    profileVisibility: 'Видимость профиля', profileVisibilityDesc: 'Разрешить другим пользователям вашего региона просматривать профиль',
    financePortalTitle: 'Финансовый портал', reportingPortalTitle: 'Портал отчётов',
    auditLogsTitle: 'Журналы аудита',
  },

  // ─── NEW: Mandarin Chinese ────────────────────────────────────────────────
  Chinese: {
    dashboard: '仪表板', reportingPortal: '报告门户',
    financePortal: '财务门户', analytics: '数据分析',
    auditLogs: '审计日志', userManagement: '用户管理',
    magazine: '杂志', notifications: '通知', settings: '设置',
    welcomeBack: '欢迎回来', today: '今天',
    weeklyReminderTitle: '每周报告提醒',
    weeklyReminderDesc: '请记得在周四结束前提交您的每周报告。',
    totalReports: '报告总数', totalFinance: '财务总额',
    totalAttendance: '出勤总数', completionRate: '完成率',
    newMembers: '新成员', avgAttendance: '平均出勤',
    recentActivity: '最近活动', search: '搜索...',
    filters: '筛选', showingReports: '显示', reports: '份报告',
    submitReport: '提交报告', addEntry: '添加条目',
    uploadCSV: '上传 CSV/Excel', export: '导出',
    view: '查看', download: '下载', actions: '操作',
    status: '状态', date: '日期', region: '地区', zone: '区域',
    campaign: '活动', submittedBy: '提交者', attendance: '出勤',
    notes: '备注', reportId: '报告编号',
    totalRecords: '记录总数', totalAmount: '总金额',
    avgAmount: '平均金额', category: '类别', amount: '金额',
    entryId: '条目编号',
    totalActivities: '活动总数', activeUsers: '活跃用户',
    modules: '模块', user: '用户', action: '操作',
    module: '模块', previousValue: '原始值', updatedValue: '更新值',
    timestamp: '时间戳',
    signOut: '退出登录', signIn: '登录', signUp: '注册',
    email: '电子邮件', password: '密码', fullName: '全名',
    saveChanges: '保存更改', cancel: '取消', close: '关闭',
    placeOrder: '下订单', backToOrders: '返回订单',
    campaignPerformance: '活动表现',
    monthlyTrends: '月度趋势', regionStats: '地区统计',
    analyticsDashboard: '分析仪表板',
    attendanceTrend: '出勤趋势', financeTrend: '财务趋势',
    regionalComparison: '地区对比', campaignDistribution: '活动分布',
    attendanceSummary: '按地区出勤汇总', timeRange: '时间范围',
    markAllRead: '全部标为已读',
    all: '全部', unread: '未读', new: '新',
    noNotifications: '暂无通知', markAsRead: '标为已读',
    settingsTitle: '设置', settingsDesc: '管理您的账户偏好和配置',
    profile: '个人资料', security: '安全', preferences: '偏好设置', privacy: '隐私',
    profileInfo: '个人信息', profileInfoDesc: '更新您的个人详情和联系方式',
    firstName: '名字', lastName: '姓氏', emailAddress: '电子邮件地址',
    phoneNumber: '电话号码', timezone: '时区', role: '角色', region: '地区',
    changePhoto: '更换照片', remove: '移除',
    securityTitle: '安全', securityDesc: '管理您的密码和账户安全',
    changePassword: '更改密码', currentPassword: '当前密码',
    newPassword: '新密码', confirmPassword: '确认密码',
    updatePassword: '更新密码', twoFactor: '双重身份验证',
    twoFactorDesc: '为您的账户添加额外的安全保障。',
    enable2FA: '启用双重验证', enabled: '已启用', disabled: '已禁用',
    activeSessions: '活动会话', activeSessionsDesc: '当前已登录您账户的设备。',
    current: '当前', revoke: '撤销',
    notifPrefs: '通知偏好', notifPrefsDesc: '选择您希望收到哪些通知',
    savePreferences: '保存偏好',
    preferencesTitle: '偏好设置', preferencesDesc: '自定义您的平台体验',
    display: '显示', language: '语言', dateFormat: '日期格式', currency: '货币',
    theme: '主题', themeDesc: '更改将立即应用于整个应用程序。',
    light: '浅色', dark: '深色', system: '跟随系统',
    privacyTitle: '隐私', privacyDesc: '控制您的数据和隐私设置',
    dataActivity: '数据与活动', dangerZone: '危险区域',
    dangerZoneDesc: '这些操作是永久性的，无法撤销。',
    deleteAccount: '删除账户', deleteAccountDesc: '永久删除您的账户及所有相关数据',
    activityLogging: '活动记录', activityLoggingDesc: '允许平台记录您的活动以供审计',
    analyticsTracking: '分析跟踪', analyticsTrackingDesc: '共享匿名使用数据以帮助改进平台',
    profileVisibility: '个人资料可见性', profileVisibilityDesc: '允许您所在地区的其他用户查看您的个人资料',
    financePortalTitle: '财务门户', reportingPortalTitle: '报告门户',
    auditLogsTitle: '审计日志',
  },

  // ─── NEW: Bengali ─────────────────────────────────────────────────────────
  Bengali: {
    dashboard: 'ড্যাশবোর্ড', reportingPortal: 'রিপোর্টিং পোর্টাল',
    financePortal: 'অর্থ পোর্টাল', analytics: 'বিশ্লেষণ',
    auditLogs: 'অডিট লগ', userManagement: 'ব্যবহারকারী ব্যবস্থাপনা',
    magazine: 'ম্যাগাজিন', notifications: 'বিজ্ঞপ্তি', settings: 'সেটিংস',
    welcomeBack: 'স্বাগত ফিরে', today: 'আজ',
    weeklyReminderTitle: 'সাপ্তাহিক রিপোর্ট অনুস্মারক',
    weeklyReminderDesc: 'বৃহস্পতিবারের মধ্যে আপনার সাপ্তাহিক রিপোর্ট জমা দিতে ভুলবেন না।',
    totalReports: 'মোট রিপোর্ট', totalFinance: 'মোট অর্থ',
    totalAttendance: 'মোট উপস্থিতি', completionRate: 'সম্পন্নের হার',
    newMembers: 'নতুন সদস্য', avgAttendance: 'গড় উপস্থিতি',
    recentActivity: 'সাম্প্রতিক কার্যক্রম', search: 'খুঁজুন...',
    filters: 'ফিল্টার', showingReports: 'দেখানো হচ্ছে', reports: 'রিপোর্ট',
    submitReport: 'রিপোর্ট জমা দিন', addEntry: 'এন্ট্রি যোগ করুন',
    uploadCSV: 'CSV/Excel আপলোড করুন', export: 'রপ্তানি করুন',
    view: 'দেখুন', download: 'ডাউনলোড', actions: 'কার্যক্রম',
    status: 'অবস্থা', date: 'তারিখ', region: 'অঞ্চল', zone: 'জোন',
    campaign: 'প্রচারণা', submittedBy: 'জমাদানকারী', attendance: 'উপস্থিতি',
    notes: 'নোট', reportId: 'রিপোর্ট আইডি',
    totalRecords: 'মোট রেকর্ড', totalAmount: 'মোট পরিমাণ',
    avgAmount: 'গড় পরিমাণ', category: 'বিভাগ', amount: 'পরিমাণ',
    entryId: 'এন্ট্রি আইডি',
    totalActivities: 'মোট কার্যক্রম', activeUsers: 'সক্রিয় ব্যবহারকারী',
    modules: 'মডিউল', user: 'ব্যবহারকারী', action: 'কার্যক্রম',
    module: 'মডিউল', previousValue: 'পূর্ববর্তী মান', updatedValue: 'আপডেটকৃত মান',
    timestamp: 'টাইমস্ট্যাম্প',
    signOut: 'সাইন আউট', signIn: 'সাইন ইন', signUp: 'সাইন আপ',
    email: 'ইমেইল', password: 'পাসওয়ার্ড', fullName: 'পুরো নাম',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন', cancel: 'বাতিল', close: 'বন্ধ করুন',
    placeOrder: 'অর্ডার দিন', backToOrders: 'অর্ডারে ফিরুন',
    campaignPerformance: 'প্রচারণার কার্যকারিতা',
    monthlyTrends: 'মাসিক প্রবণতা', regionStats: 'অঞ্চলভিত্তিক পরিসংখ্যান',
    analyticsDashboard: 'বিশ্লেষণ ড্যাশবোর্ড',
    attendanceTrend: 'উপস্থিতি প্রবণতা', financeTrend: 'আর্থিক প্রবণতা',
    regionalComparison: 'আঞ্চলিক তুলনা', campaignDistribution: 'প্রচারণা বিতরণ',
    attendanceSummary: 'অঞ্চলভিত্তিক উপস্থিতির সারসংক্ষেপ', timeRange: 'সময় পরিসীমা',
    markAllRead: 'সব পঠিত হিসেবে চিহ্নিত করুন',
    all: 'সব', unread: 'অপঠিত', new: 'নতুন',
    noNotifications: 'কোনো বিজ্ঞপ্তি নেই', markAsRead: 'পঠিত চিহ্নিত করুন',
    settingsTitle: 'সেটিংস', settingsDesc: 'আপনার অ্যাকাউন্টের পছন্দ এবং কনফিগারেশন পরিচালনা করুন',
    profile: 'প্রোফাইল', security: 'নিরাপত্তা', preferences: 'পছন্দ', privacy: 'গোপনীয়তা',
    profileInfo: 'প্রোফাইল তথ্য', profileInfoDesc: 'আপনার ব্যক্তিগত তথ্য আপডেট করুন',
    firstName: 'প্রথম নাম', lastName: 'শেষ নাম', emailAddress: 'ইমেইল ঠিকানা',
    phoneNumber: 'ফোন নম্বর', timezone: 'টাইমজোন', role: 'ভূমিকা', region: 'অঞ্চল',
    changePhoto: 'ছবি পরিবর্তন করুন', remove: 'সরান',
    securityTitle: 'নিরাপত্তা', securityDesc: 'আপনার পাসওয়ার্ড এবং অ্যাকাউন্টের নিরাপত্তা পরিচালনা করুন',
    changePassword: 'পাসওয়ার্ড পরিবর্তন করুন', currentPassword: 'বর্তমান পাসওয়ার্ড',
    newPassword: 'নতুন পাসওয়ার্ড', confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    updatePassword: 'পাসওয়ার্ড আপডেট করুন', twoFactor: 'দ্বি-স্তর যাচাইকরণ',
    twoFactorDesc: 'আপনার অ্যাকাউন্টে অতিরিক্ত নিরাপত্তা স্তর যোগ করুন।',
    enable2FA: '2FA সক্ষম করুন', enabled: 'সক্ষম', disabled: 'অক্ষম',
    activeSessions: 'সক্রিয় সেশন', activeSessionsDesc: 'বর্তমানে আপনার অ্যাকাউন্টে লগইন ডিভাইসগুলি।',
    current: 'বর্তমান', revoke: 'বাতিল করুন',
    notifPrefs: 'বিজ্ঞপ্তির পছন্দ', notifPrefsDesc: 'আপনি কোন বিষয়ে বিজ্ঞপ্তি পেতে চান তা বেছে নিন',
    savePreferences: 'পছন্দ সংরক্ষণ করুন',
    preferencesTitle: 'পছন্দ', preferencesDesc: 'আপনার প্ল্যাটফর্ম অভিজ্ঞতা কাস্টমাইজ করুন',
    display: 'প্রদর্শন', language: 'ভাষা', dateFormat: 'তারিখের ফর্ম্যাট', currency: 'মুদ্রা',
    theme: 'থিম', themeDesc: 'পরিবর্তনগুলি সম্পূর্ণ অ্যাপে তাৎক্ষণিকভাবে প্রযোজ্য হয়।',
    light: 'হালকা', dark: 'গাঢ়', system: 'সিস্টেম',
    privacyTitle: 'গোপনীয়তা', privacyDesc: 'আপনার ডেটা এবং গোপনীয়তা সেটিংস নিয়ন্ত্রণ করুন',
    dataActivity: 'ডেটা ও কার্যক্রম', dangerZone: 'বিপদজনক অঞ্চল',
    dangerZoneDesc: 'এই কার্যক্রমগুলি স্থায়ী এবং পূর্বাবস্থায় ফেরানো যাবে না।',
    deleteAccount: 'অ্যাকাউন্ট মুছুন', deleteAccountDesc: 'আপনার অ্যাকাউন্ট এবং সমস্ত সম্পর্কিত ডেটা স্থায়ীভাবে মুছুন',
    activityLogging: 'কার্যক্রম লগিং', activityLoggingDesc: 'অডিটের জন্য প্ল্যাটফর্মকে আপনার কার্যক্রম লগ করতে দিন',
    analyticsTracking: 'বিশ্লেষণ ট্র্যাকিং', analyticsTrackingDesc: 'প্ল্যাটফর্ম উন্নত করতে বেনামী ব্যবহারের ডেটা শেয়ার করুন',
    profileVisibility: 'প্রোফাইল দৃশ্যমানতা', profileVisibilityDesc: 'আপনার অঞ্চলের অন্যান্য ব্যবহারকারীদের আপনার প্রোফাইল দেখতে দিন',
    financePortalTitle: 'অর্থ পোর্টাল', reportingPortalTitle: 'রিপোর্টিং পোর্টাল',
    auditLogsTitle: 'অডিট লগ',
  },

  // ─── NEW: Arabic (Modern Standard — RTL) ─────────────────────────────────
  Arabic: {
    dashboard: 'لوحة التحكم', reportingPortal: 'بوابة التقارير',
    financePortal: 'البوابة المالية', analytics: 'التحليلات',
    auditLogs: 'سجلات التدقيق', userManagement: 'إدارة المستخدمين',
    magazine: 'المجلة', notifications: 'الإشعارات', settings: 'الإعدادات',
    welcomeBack: 'مرحباً بعودتك', today: 'اليوم',
    weeklyReminderTitle: 'تذكير بالتقرير الأسبوعي',
    weeklyReminderDesc: 'لا تنسَ تقديم تقريرك الأسبوعي قبل نهاية يوم الخميس.',
    totalReports: 'إجمالي التقارير', totalFinance: 'إجمالي المالية',
    totalAttendance: 'إجمالي الحضور', completionRate: 'معدل الإنجاز',
    newMembers: 'أعضاء جدد', avgAttendance: 'متوسط الحضور',
    recentActivity: 'النشاط الأخير', search: 'بحث...',
    filters: 'تصفية', showingReports: 'عرض', reports: 'تقارير',
    submitReport: 'إرسال التقرير', addEntry: 'إضافة إدخال',
    uploadCSV: 'رفع CSV/Excel', export: 'تصدير',
    view: 'عرض', download: 'تنزيل', actions: 'إجراءات',
    status: 'الحالة', date: 'التاريخ', region: 'المنطقة', zone: 'النطاق',
    campaign: 'الحملة', submittedBy: 'مقدَّم بواسطة', attendance: 'الحضور',
    notes: 'ملاحظات', reportId: 'معرّف التقرير',
    totalRecords: 'إجمالي السجلات', totalAmount: 'المبلغ الإجمالي',
    avgAmount: 'المبلغ المتوسط', category: 'الفئة', amount: 'المبلغ',
    entryId: 'معرّف الإدخال',
    totalActivities: 'إجمالي الأنشطة', activeUsers: 'المستخدمون النشطون',
    modules: 'الوحدات', user: 'المستخدم', action: 'الإجراء',
    module: 'الوحدة', previousValue: 'القيمة السابقة', updatedValue: 'القيمة المحدَّثة',
    timestamp: 'الطابع الزمني',
    signOut: 'تسجيل الخروج', signIn: 'تسجيل الدخول', signUp: 'إنشاء حساب',
    email: 'البريد الإلكتروني', password: 'كلمة المرور', fullName: 'الاسم الكامل',
    saveChanges: 'حفظ التغييرات', cancel: 'إلغاء', close: 'إغلاق',
    placeOrder: 'تقديم الطلب', backToOrders: 'العودة إلى الطلبات',
    campaignPerformance: 'أداء الحملة',
    monthlyTrends: 'الاتجاهات الشهرية', regionStats: 'إحصائيات المنطقة',
    analyticsDashboard: 'لوحة التحليلات',
    attendanceTrend: 'اتجاه الحضور', financeTrend: 'الاتجاه المالي',
    regionalComparison: 'المقارنة الإقليمية', campaignDistribution: 'توزيع الحملة',
    attendanceSummary: 'ملخص الحضور حسب المنطقة', timeRange: 'النطاق الزمني',
    markAllRead: 'تحديد الكل كمقروء',
    all: 'الكل', unread: 'غير مقروء', new: 'جديد',
    noNotifications: 'لا توجد إشعارات', markAsRead: 'تحديد كمقروء',
    settingsTitle: 'الإعدادات', settingsDesc: 'إدارة تفضيلات حسابك وإعداداته',
    profile: 'الملف الشخصي', security: 'الأمان', preferences: 'التفضيلات', privacy: 'الخصوصية',
    profileInfo: 'معلومات الملف الشخصي', profileInfoDesc: 'تحديث بياناتك الشخصية ومعلومات الاتصال',
    firstName: 'الاسم الأول', lastName: 'اسم العائلة', emailAddress: 'عنوان البريد الإلكتروني',
    phoneNumber: 'رقم الهاتف', timezone: 'المنطقة الزمنية', role: 'الدور', region: 'المنطقة',
    changePhoto: 'تغيير الصورة', remove: 'إزالة',
    securityTitle: 'الأمان', securityDesc: 'إدارة كلمة المرور وأمان الحساب',
    changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة', confirmPassword: 'تأكيد كلمة المرور',
    updatePassword: 'تحديث كلمة المرور', twoFactor: 'المصادقة الثنائية',
    twoFactorDesc: 'أضف طبقة أمان إضافية لحسابك.',
    enable2FA: 'تفعيل المصادقة الثنائية', enabled: 'مفعَّل', disabled: 'معطَّل',
    activeSessions: 'الجلسات النشطة', activeSessionsDesc: 'الأجهزة المسجَّل دخولها حالياً في حسابك.',
    current: 'الحالي', revoke: 'إلغاء',
    notifPrefs: 'تفضيلات الإشعارات', notifPrefsDesc: 'اختر ما تريد تلقّي إشعارات بشأنه',
    savePreferences: 'حفظ التفضيلات',
    preferencesTitle: 'التفضيلات', preferencesDesc: 'تخصيص تجربتك على المنصة',
    display: 'العرض', language: 'اللغة', dateFormat: 'تنسيق التاريخ', currency: 'العملة',
    theme: 'المظهر', themeDesc: 'تُطبَّق التغييرات فوراً على كامل التطبيق.',
    light: 'فاتح', dark: 'داكن', system: 'النظام',
    privacyTitle: 'الخصوصية', privacyDesc: 'التحكم في بياناتك وإعدادات الخصوصية',
    dataActivity: 'البيانات والنشاط', dangerZone: 'المنطقة الخطرة',
    dangerZoneDesc: 'هذه الإجراءات دائمة ولا يمكن التراجع عنها.',
    deleteAccount: 'حذف الحساب', deleteAccountDesc: 'حذف حسابك وجميع البيانات المرتبطة به نهائياً',
    activityLogging: 'تسجيل النشاط', activityLoggingDesc: 'السماح للمنصة بتسجيل نشاطك لأغراض التدقيق',
    analyticsTracking: 'تتبع التحليلات', analyticsTrackingDesc: 'مشاركة بيانات الاستخدام المجهولة لتحسين المنصة',
    profileVisibility: 'إمكانية رؤية الملف الشخصي', profileVisibilityDesc: 'السماح للمستخدمين الآخرين في منطقتك برؤية ملفك الشخصي',
    financePortalTitle: 'البوابة المالية', reportingPortalTitle: 'بوابة التقارير',
    auditLogsTitle: 'سجلات التدقيق',
  },

  // ─── NEW: Indonesian ──────────────────────────────────────────────────────
  Indonesian: {
    dashboard: 'Dasbor', reportingPortal: 'Portal Pelaporan',
    financePortal: 'Portal Keuangan', analytics: 'Analitik',
    auditLogs: 'Log Audit', userManagement: 'Manajemen Pengguna',
    magazine: 'Majalah', notifications: 'Notifikasi', settings: 'Pengaturan',
    welcomeBack: 'Selamat datang kembali', today: 'Hari ini',
    weeklyReminderTitle: 'Pengingat Laporan Mingguan',
    weeklyReminderDesc: 'Jangan lupa kirimkan laporan mingguan Anda sebelum akhir hari Kamis.',
    totalReports: 'Total Laporan', totalFinance: 'Total Keuangan',
    totalAttendance: 'Total Kehadiran', completionRate: 'Tingkat Penyelesaian',
    newMembers: 'Anggota Baru', avgAttendance: 'Rata-rata Kehadiran',
    recentActivity: 'Aktivitas Terkini', search: 'Cari...',
    filters: 'Filter', showingReports: 'Menampilkan', reports: 'laporan',
    submitReport: 'Kirim Laporan', addEntry: 'Tambah Entri',
    uploadCSV: 'Unggah CSV/Excel', export: 'Ekspor',
    view: 'Lihat', download: 'Unduh', actions: 'Tindakan',
    status: 'Status', date: 'Tanggal', region: 'Wilayah', zone: 'Zona',
    campaign: 'Kampanye', submittedBy: 'Dikirim Oleh', attendance: 'Kehadiran',
    notes: 'Catatan', reportId: 'ID Laporan',
    totalRecords: 'Total Catatan', totalAmount: 'Total Jumlah',
    avgAmount: 'Jumlah Rata-rata', category: 'Kategori', amount: 'Jumlah',
    entryId: 'ID Entri',
    totalActivities: 'Total Aktivitas', activeUsers: 'Pengguna Aktif',
    modules: 'Modul', user: 'Pengguna', action: 'Tindakan',
    module: 'Modul', previousValue: 'Nilai Sebelumnya', updatedValue: 'Nilai Diperbarui',
    timestamp: 'Cap Waktu',
    signOut: 'Keluar', signIn: 'Masuk', signUp: 'Daftar',
    email: 'Email', password: 'Kata Sandi', fullName: 'Nama Lengkap',
    saveChanges: 'Simpan Perubahan', cancel: 'Batal', close: 'Tutup',
    placeOrder: 'Buat Pesanan', backToOrders: 'Kembali ke Pesanan',
    campaignPerformance: 'Kinerja Kampanye',
    monthlyTrends: 'Tren Bulanan', regionStats: 'Statistik Per Wilayah',
    analyticsDashboard: 'Dasbor Analitik',
    attendanceTrend: 'Tren Kehadiran', financeTrend: 'Tren Keuangan',
    regionalComparison: 'Perbandingan Regional', campaignDistribution: 'Distribusi Kampanye',
    attendanceSummary: 'Ringkasan Kehadiran per Wilayah', timeRange: 'Rentang Waktu',
    markAllRead: 'Tandai Semua Sudah Dibaca',
    all: 'Semua', unread: 'Belum Dibaca', new: 'Baru',
    noNotifications: 'Tidak ada notifikasi', markAsRead: 'Tandai sudah dibaca',
    settingsTitle: 'Pengaturan', settingsDesc: 'Kelola preferensi dan konfigurasi akun Anda',
    profile: 'Profil', security: 'Keamanan', preferences: 'Preferensi', privacy: 'Privasi',
    profileInfo: 'Informasi Profil', profileInfoDesc: 'Perbarui detail pribadi dan informasi kontak Anda',
    firstName: 'Nama Depan', lastName: 'Nama Belakang', emailAddress: 'Alamat Email',
    phoneNumber: 'Nomor Telepon', timezone: 'Zona Waktu', role: 'Peran', region: 'Wilayah',
    changePhoto: 'Ganti Foto', remove: 'Hapus',
    securityTitle: 'Keamanan', securityDesc: 'Kelola kata sandi dan keamanan akun Anda',
    changePassword: 'Ganti Kata Sandi', currentPassword: 'Kata Sandi Saat Ini',
    newPassword: 'Kata Sandi Baru', confirmPassword: 'Konfirmasi Kata Sandi',
    updatePassword: 'Perbarui Kata Sandi', twoFactor: 'Autentikasi Dua Faktor',
    twoFactorDesc: 'Tambahkan lapisan keamanan ekstra untuk akun Anda.',
    enable2FA: 'Aktifkan 2FA', enabled: 'Aktif', disabled: 'Nonaktif',
    activeSessions: 'Sesi Aktif', activeSessionsDesc: 'Perangkat yang sedang masuk ke akun Anda.',
    current: 'Saat Ini', revoke: 'Cabut',
    notifPrefs: 'Preferensi Notifikasi', notifPrefsDesc: 'Pilih hal yang ingin Anda dapatkan notifikasinya',
    savePreferences: 'Simpan Preferensi',
    preferencesTitle: 'Preferensi', preferencesDesc: 'Sesuaikan pengalaman platform Anda',
    display: 'Tampilan', language: 'Bahasa', dateFormat: 'Format Tanggal', currency: 'Mata Uang',
    theme: 'Tema', themeDesc: 'Perubahan langsung diterapkan di seluruh aplikasi.',
    light: 'Terang', dark: 'Gelap', system: 'Sistem',
    privacyTitle: 'Privasi', privacyDesc: 'Kendalikan data dan pengaturan privasi Anda',
    dataActivity: 'Data & Aktivitas', dangerZone: 'Zona Berbahaya',
    dangerZoneDesc: 'Tindakan ini bersifat permanen dan tidak dapat dibatalkan.',
    deleteAccount: 'Hapus Akun', deleteAccountDesc: 'Hapus akun dan semua data terkait secara permanen',
    activityLogging: 'Pencatatan aktivitas', activityLoggingDesc: 'Izinkan platform mencatat aktivitas Anda untuk keperluan audit',
    analyticsTracking: 'Pelacakan analitik', analyticsTrackingDesc: 'Bagikan data penggunaan anonim untuk membantu meningkatkan platform',
    profileVisibility: 'Visibilitas profil', profileVisibilityDesc: 'Izinkan pengguna lain di wilayah Anda melihat profil Anda',
    financePortalTitle: 'Portal Keuangan', reportingPortalTitle: 'Portal Pelaporan',
    auditLogsTitle: 'Log Audit',
  },
};

const SettingsContext = createContext(null);

export function SettingsProvider({ children }) {
  const [settings, setSettings] = useState(() => {
    const loaded = loadSettings();
    applyTheme(loaded.preferences.theme);
    return loaded;
  });

  useEffect(() => {
    sessionStorage.setItem(STORAGE_KEY, JSON.stringify(settings));
  }, [settings]);

  useEffect(() => {
    applyTheme(settings.preferences.theme);
  }, [settings.preferences.theme]);

  // Apply RTL direction when Arabic is selected
  useEffect(() => {
    const isRTL = RTL_LANGUAGES.has(settings.preferences.language);
    document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', LANGUAGE_LOCALE_MAP[settings.preferences.language] || 'en-US');
  }, [settings.preferences.language]);

  useEffect(() => {
    if (settings.preferences.theme !== 'system') return;
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = (e) => {
      document.documentElement.setAttribute('data-theme', e.matches ? 'dark' : 'light');
    };
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, [settings.preferences.theme]);

  const updateSection = (section, values) => {
    setSettings(prev => ({
      ...prev,
      [section]: { ...prev[section], ...values },
    }));
  };

  // Convenience helpers derived from preferences
  const language   = settings.preferences.language   || 'English';
  const dateFormat = settings.preferences.dateFormat || 'MM/DD/YYYY';
  const currency   = settings.preferences.currency   || 'USD ($)';
  const isRTL      = RTL_LANGUAGES.has(language);

  const t          = TRANSLATIONS[language] || TRANSLATIONS.English;
  const formatDate = DATE_FORMAT_FN[dateFormat] || DATE_FORMAT_FN['MM/DD/YYYY'];
  const currSymbol = CURRENCY_SYMBOL_MAP[currency] || '$';

  return (
    <SettingsContext.Provider value={{
      settings, updateSection,
      t, formatDate, currSymbol, language, dateFormat, currency, isRTL,
    }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  return useContext(SettingsContext);
}
